import type * as DocsPlugin from '@docusaurus/plugin-content-docs';

export default {
  
    // default https://docusaurus.io/docs/sidebar/autogenerated sidebar slice based on hierarchy under docs/
    refarchSidebar: [ { type: 'autogenerated', dirName: '.' } ],
   
    // custom auto-generated sidebar slices - see src/_scripts/_sidebarGenerator.js
    // dirname is used for matching/filtering documents based on tags
    exploreallrefarch: [{ type: "autogenerated", dirName: 'exploreallrefarch' }],
    azure: [ { type: 'autogenerated', dirName: 'azure' } ],
    aws: [ { type: 'autogenerated', dirName: 'aws' } ],
    gcp: [ { type: 'autogenerated', dirName: 'gcp' } ],
    appdev: [ { type: 'autogenerated', dirName: 'appdev' } ],
    ai: [ { type: 'autogenerated', dirName: 'ai' } ],
    data: [ { type: 'autogenerated', dirName: 'data' } ],
    integration: [ { type: 'autogenerated', dirName: 'integration' } ],
    opsec: [ { type: 'autogenerated', dirName: 'opsec' } ]
  
  } satisfies DocsPlugin.SidebarsConfig;
