import type * as DocsPlugin from '@docusaurus/plugin-content-docs';

export default {
    communitySidebar: [
        {
            type: 'autogenerated',
            dirName: '.',
        },
    ],
} satisfies DocsPlugin.SidebarsConfig;
