module.exports = {
  communitySidebar:
    // ISAM
    /*
    {
      type: "category",
      label: "ISAM",
      className: "category-as-header",
      items: [
        {
          type: "doc",
          id: "sap_integration_solution_advisory_methodology_cloud_v2/index",
          label: "ISAM Overview",
        },
      ],
    },
    */
    [
      {
        type: 'autogenerated',
        dirName: '.'
      }
    ],
  guidance: [{ type: 'autogenerated', dirName: 'guidance' }]
};